### ISSUE TITLE
Host images for this repository

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/deviser#7]
This issue exists to host images for this repository.

<img width="886" alt="deviser" src="https://user-images.githubusercontent.com/378235/27263697-1ba9bd94-546f-11e7-87e3-30fc77731a19.png">

**Comment by sindrenm** [comment]
Sneaky! :smirk:

**Comment by timkurvers** [comment]
😄

**Comment by jgorset** [comment]
Haha, yeah!
